# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GonzagaCampusWalkingTour' do
  # Comment the next line if you don't want to use dynamic frameworks
 # use_frameworks!
use_modular_headers!

  # Pods for GonzagaCampusWalkingTour
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase/Core'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'Firebase/Database' 
  pod 'Firebase/Storage'
  pod 'SwiftSoup'

  target 'GonzagaCampusWalkingTourTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
